[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/auth/callback?next=/dashboard&recovery=1",
  "http://localhost:3000/reset-password",
  "https://wavedata.asia/auth/callback",
  "https://wavedata.asia/auth/callback?next=/dashboard&recovery=1",
  "https://wavedata.asia/reset-password",
]

[auth.email.smtp]
sender_name = "海浪资讯"

[auth.email.template.confirmation]
subject = "【海浪资讯】请验证你的邮箱"
content_path = "./email-templates/confirmation.html"
